Seleciona colunas
Converter em lista (Botao direito)
Converter em tabela
, na ultima linha do let


NewRows = Table.InsertRows(#"passo interior", index da linha, {[Coluna = "Novo Dado"]}) as table

NewRows = Table.InsertRows(#"passo interior", index da linha, {[Coluna = "Novo Dado", index = 7], [Coluna = "Novo Dado", index = 8]}) as table

NewRows = Table.InsertRows(table as table, offset as number, rows as list) as table

Table.InsertRows(Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}), 1, {[CustomerID = 2, Name = "Jim", Phone = "987-6543"],[CustomerID = 3, Name = "Paul", Phone = "543-7890"] })

